// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppCloseWindow() {
  return window['go']['main']['App']['AppCloseWindow']();
}

export function AppMinimizeWindow() {
  return window['go']['main']['App']['AppMinimizeWindow']();
}

export function AppToggleMaximizeWindow() {
  return window['go']['main']['App']['AppToggleMaximizeWindow']();
}

export function DayzApplyInitGenerator(arg1) {
  return window['go']['main']['App']['DayzApplyInitGenerator'](arg1);
}

export function DayzAutoDetectServerPaths() {
  return window['go']['main']['App']['DayzAutoDetectServerPaths']();
}

export function DayzBackupInitGenerator(arg1) {
  return window['go']['main']['App']['DayzBackupInitGenerator'](arg1);
}

export function DayzDeleteCrashArtifacts(arg1) {
  return window['go']['main']['App']['DayzDeleteCrashArtifacts'](arg1);
}

export function DayzDeleteMod(arg1) {
  return window['go']['main']['App']['DayzDeleteMod'](arg1);
}

export function DayzDetectClientExecutable() {
  return window['go']['main']['App']['DayzDetectClientExecutable']();
}

export function DayzDetectServerPaths(arg1) {
  return window['go']['main']['App']['DayzDetectServerPaths'](arg1);
}

export function DayzGetClientRuntime() {
  return window['go']['main']['App']['DayzGetClientRuntime']();
}

export function DayzGetServerRuntime() {
  return window['go']['main']['App']['DayzGetServerRuntime']();
}

export function DayzGetWorkspaceState() {
  return window['go']['main']['App']['DayzGetWorkspaceState']();
}

export function DayzInspectModFolder(arg1) {
  return window['go']['main']['App']['DayzInspectModFolder'](arg1);
}

export function DayzLaunchClient(arg1) {
  return window['go']['main']['App']['DayzLaunchClient'](arg1);
}

export function DayzOpenPath(arg1) {
  return window['go']['main']['App']['DayzOpenPath'](arg1);
}

export function DayzPickExecutable(arg1) {
  return window['go']['main']['App']['DayzPickExecutable'](arg1);
}

export function DayzPickFolder(arg1) {
  return window['go']['main']['App']['DayzPickFolder'](arg1);
}

export function DayzPreviewInitGenerator(arg1) {
  return window['go']['main']['App']['DayzPreviewInitGenerator'](arg1);
}

export function DayzReadMissionSessionSettings(arg1) {
  return window['go']['main']['App']['DayzReadMissionSessionSettings'](arg1);
}

export function DayzReadServerConfig(arg1) {
  return window['go']['main']['App']['DayzReadServerConfig'](arg1);
}

export function DayzRestartServer(arg1) {
  return window['go']['main']['App']['DayzRestartServer'](arg1);
}

export function DayzSaveWorkspaceState(arg1) {
  return window['go']['main']['App']['DayzSaveWorkspaceState'](arg1);
}

export function DayzScanCrashTools(arg1) {
  return window['go']['main']['App']['DayzScanCrashTools'](arg1);
}

export function DayzScanMissions(arg1) {
  return window['go']['main']['App']['DayzScanMissions'](arg1);
}

export function DayzScanMods(arg1) {
  return window['go']['main']['App']['DayzScanMods'](arg1);
}

export function DayzScanWorkshopMods(arg1) {
  return window['go']['main']['App']['DayzScanWorkshopMods'](arg1);
}

export function DayzStartServer(arg1) {
  return window['go']['main']['App']['DayzStartServer'](arg1);
}

export function DayzStopClient() {
  return window['go']['main']['App']['DayzStopClient']();
}

export function DayzStopServer() {
  return window['go']['main']['App']['DayzStopServer']();
}

export function DayzWriteServerConfig(arg1) {
  return window['go']['main']['App']['DayzWriteServerConfig'](arg1);
}
