// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppCloseWindow():Promise<void>;

export function AppMinimizeWindow():Promise<void>;

export function AppToggleMaximizeWindow():Promise<boolean>;

export function DayzApplyInitGenerator(arg1:any):Promise<any>;

export function DayzAutoDetectServerPaths():Promise<any>;

export function DayzBackupInitGenerator(arg1:any):Promise<any>;

export function DayzDeleteCrashArtifacts(arg1:any):Promise<any>;

export function DayzDeleteMod(arg1:any):Promise<any>;

export function DayzDetectClientExecutable():Promise<string>;

export function DayzDetectServerPaths(arg1:string):Promise<any>;

export function DayzGetClientRuntime():Promise<any>;

export function DayzGetServerRuntime():Promise<any>;

export function DayzGetWorkspaceState():Promise<any>;

export function DayzInspectModFolder(arg1:string):Promise<any>;

export function DayzLaunchClient(arg1:any):Promise<any>;

export function DayzOpenPath(arg1:string):Promise<void>;

export function DayzPickExecutable(arg1:main.PickPathOptions):Promise<string>;

export function DayzPickFolder(arg1:main.PickPathOptions):Promise<string>;

export function DayzPreviewInitGenerator(arg1:any):Promise<any>;

export function DayzReadMissionSessionSettings(arg1:string):Promise<any>;

export function DayzReadServerConfig(arg1:string):Promise<any>;

export function DayzRestartServer(arg1:any):Promise<any>;

export function DayzSaveWorkspaceState(arg1:any):Promise<any>;

export function DayzScanCrashTools(arg1:any):Promise<any>;

export function DayzScanMissions(arg1:string):Promise<any>;

export function DayzScanMods(arg1:string):Promise<any>;

export function DayzScanWorkshopMods(arg1:string):Promise<any>;

export function DayzStartServer(arg1:any):Promise<any>;

export function DayzStopClient():Promise<any>;

export function DayzStopServer():Promise<any>;

export function DayzWriteServerConfig(arg1:any):Promise<any>;
